B904: ensure the raise is in the same context with the except
PyCQA/flake8-bugbear pull request #191
Opened 2021-10-05 07:20 UTC by isidentical

Resolves #190. Introduces a simple version of context management, though more detailed analysis might need something a little bit specialized in the future (e.g [stuff like this](https://github.com/isidentical/refactor/blob/1178e9faee21227b5f73f8815724cf9bae048200/refactor/context.py#L165-L177)).

2021-10-05 16:11 UTC, cooperlees commented
@Zac-HD - Thoughts?

@isidentical - Sorry - we run black formatting with an experimental feature:
- To fix: `black --check --experimental-string-processing .`

2021-10-05 16:14 UTC, isidentical commented
@cooperlees ah, my bad. By the way, is there a particular reason why this project doesn't use `pre-commit` (or some other script) to do these stuff? If there is none, I can create a patch about it.

2021-10-05 23:58 UTC, Zac-HD commented
The concept sounds good to me, though the diff looks like it's patching B902 instead of B904?

(this also seems pretty rare to me, but as a general rule "if someone provides a patch, it matters enough to merge")

2021-10-06 06:43 UTC, isidentical commented
No actually not, I do not need to change anything on the B904's implementation, since it just checks if there are any except handlers within the current `node_stack`. What I did was to dynamically determine the current node stack from the context (through a property). I also needed the alter the B902 to work with the new implementation but no changes on it's behavior.

2021-10-07 15:28 UTC, davidism commented
Very occasionally, a more nested pattern comes up, such as trying a backport import as well. I don't think I actually have any code that does this, but would this change also avoid the lint message in this case?

```python
try:
    from preferred_library import Thing
except ImportError:
    try:
        from fallback_library import Thing
    except ImportError:
        class Thing:
            def __getattr__(self, name):
                raise AttributeError
```

2021-10-29 18:42 UTC, cooperlees commented
This is only failing on black. I'll fix before merging. If you get time, please reformat. Otherwise I'll take care of it.

2021-11-27 16:58 UTC, cooperlees commented
@isidentical - Sorry it's taken me so long but now this with a rebase to master is unhappy. Do you have any cycles to clean this up? Was looking to release today. I'll see if I can understand too now or I might release without this and we just cut another release when you get time.

2021-11-27 17:00 UTC, cooperlees requested changes

2021-11-27 17:00 UTC, cooperlees commented on bugbear.py
> +    context = attr.ib(default=attr.Factory(list))
Is this all that is needed? How did this ever work if so :|
```suggestion
    contexts = attr.ib(default=attr.Factory(list))
```

2021-11-27 17:03 UTC, cooperlees approved these changes
Ok - That makes sense to me. Will give @isidentical a while to respond. No idea how that `self.contexts` got changed to `self.context` ... Unless it was a refactor / push error.

2021-11-28 16:52 UTC, merged