Add new check which finds duplicate except clauses
PyCQA/flake8-bugbear pull request #258
Opened 2022-05-16 09:22 UTC by kasium

Closes #254

2022-05-16 09:31 UTC, kasium commented
@cooperlees I just realized that B014 does partially the same job. The difference is, that it doesn't consider multiple except clauses. I would suggest to tune B014 to also consider multiple except's. This would mean that the error message would change. Is that fine?

2022-05-24 17:22 UTC, cooperlees commented
I think since *B014* looks for duplication per exception clause I'm a fan of the more explicit error message of the new *B023* stating that it's a redundant clause in a new except. Let me take a look at the wording to ensure this is explicit as it can be.

Thanks for asking.

2022-05-24 17:30 UTC, cooperlees requested changes
Looks good - but tests show we've hit B014 being triggered at the same time. I feel this would be annoying for users. So I feel we either extend B014 or if B023 is hit, clear B014?
- OR, do people like the two explicit errors?

I personally think getting the two lints, since they are so similar annoying - So maybe combining would be preferential?

Also, some minor suggestions in the error output + README.

2022-05-24 17:30 UTC, cooperlees commented on README.rst
> +
```suggestion
**B023**: ``try-except`` block with duplicate exceptions found.
This check identifies exception types that are specified in multiple ``except`` 
clauses. The first specification is the only one ever considered, so all others can be removed.
```

Lets try and be explicit as we can here so people can understand how to fix it.

2022-05-24 17:30 UTC, cooperlees commented on bugbear.py
> +        "B023 Exception `{0}` is catched multiple times. "
```suggestion
        "B023 Exception `{0}` has been caught multiple times. "
```

2022-09-10 20:21 UTC, kasium commented
I'm very sorry for the late pickup. Since this is heavily outdated, let me open a new PR

2022-09-10 20:21 UTC, closed without merging