Rename B028 to B907, making it optional/opinionated.
PyCQA/flake8-bugbear pull request #333
Opened 2023-01-16 13:04 UTC by jakkdl

Fixes #329 
Fixes #331 
Fixes #332

For a certain definition of "fixes" at least, the check could perhaps be improved to make it less opinionated and more useful, but silencing lots of unnecessary warnings is the first step regardless.

2023-01-16 19:23 UTC, cooperlees requested changes
Thanks for this. This is one I'm 50/50 on too. Please fix the README and I'll merge and ship asap.

2023-01-16 19:23 UTC, cooperlees commented on README.rst
> +**B907**: Consider replacing ``f"'{foo}'"`` with ``f"{foo!r}"`` which is both easier to read and will escape quotes inside ``foo`` if that would appear. The check tries to filter out any format specs
Agree

2023-01-17 14:09 UTC, jakkdl commented on README.rst
> +**B907**: Consider replacing ``f"'{foo}'"`` with ``f"{foo!r}"`` which is both easier to read and will escape quotes inside ``foo`` if that would appear. The check tries to filter out any format specs
oops, I actually had changed that but hadn't committed/pushed since.

2023-01-18 00:35 UTC, cooperlees approved these changes
LGTM - Thanks! Seems popular people want this.

2023-01-18 00:35 UTC, merged