B902: Add exceptions for standard library metaclasses
PyCQA/flake8-bugbear pull request #415
Opened 2023-09-21 11:16 UTC by henzef

I faced a false positive when deriving my metaclass from ABCMeta, which should be fixed with this commit. I also added EnumMeta to this list, because it was the only other public metaclass in the standard library.

2023-09-22 00:19 UTC, cooperlees requested changes
I'm not sure of the exact cause here, but CI is unhappy ...

2023-11-08 17:31 UTC, henzef commented
I rebased the commit to the latest main branch in the hope that it would retrigger the CI runs, but that didn't work. Now I can no longer see the origin CI results :(

2023-11-26 00:12 UTC, cooperlees approved these changes
Thanks. A worthy enhancement.

2023-11-26 00:12 UTC, cooperlees commented on tests/b024.py
> +    def method(cls):
Is there any value to have both method(self) and method2(cls)?

2023-11-26 00:12 UTC, merged